spring:
  application:
    name: NairaFlow
  
  datasource:
    url: jdbc:h2:mem:nairaflow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

jwt:
  secret: nairaflow-super-secret-key-for-jwt-token-generation-must-be-at-least-256-bits-long
  expiration: 86400000

fx:
  default-rate: 1550.00
  fee-percentage: 1.5
  rate-lock-duration: 60

app:
  cors:
    allowed-origins: http://localhost:3000